#!/usr/bin/env node
// `pnpm gen:site` — docs/policy-contract.md §8.4 "주입 방식 — 빌드 시 생성 모듈" 정본 구현.
//
// `site/site.json`(있으면) 또는 `compat/site.example.json`(없으면)으로
// `compat/compatibility.json`의 `{"$site":"<key>"}` 구멍을 채워 `src/generated/siteConstants.ts`를
// emit한다.
//
// fail-closed 3종 중 앞의 둘을 여기서 강제한다(§8.4 "부재·불량 시 동작"):
//   ① 두 사이트면이 모두 없으면 실패
//   ② 구멍이 하나라도 안 채워지면(사이트면에 필요한 키가 없으면) 실패
// (`siteProfile !== 'site'` → apply 거부/패키징 실패는 `src/core/policy/siteProfileGuard.ts`가
//  런타임/패키징 시점에 강제한다 — 이 스크립트는 산출물에 siteProfile 값만 새긴다.)
//
// `MALGN_GEN_SITE_ROOT` 환경변수로 저장소 루트를 오버라이드할 수 있다 — 이 파일의
// `main()`을 실제 파일시스템으로 end-to-end 검증하는 테스트(gen-site.test.mjs)가
// 임시 디렉터리를 저장소처럼 꾸며 이 스크립트를 그대로 spawn하기 위해서다.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const DEFAULT_ROOT = join(HERE, '..');

/**
 * `node`가 하나의 값 노드를 가리키는 구멍(`{"$site":"<key>"}`)인지 판정한다.
 */
function isHoleNode(node) {
  return (
    node !== null &&
    typeof node === 'object' &&
    !Array.isArray(node) &&
    Object.keys(node).length === 1 &&
    typeof node.$site === 'string'
  );
}

/**
 * `compatibility.json`(구멍 포함) 트리를 재귀적으로 걸어 구멍을 `siteData`의 값으로 치환한다.
 * 치환 실패(사이트면에 해당 키가 없음)는 예외를 던지지 않고 `errors`에 쌓은 뒤 구멍을
 * 그대로 남겨 둔다 — 호출자가 `hasRemainingHole()`로 "구멍 잔존"을 한 번 더 검증할 수 있게
 * 하기 위해서다(부분 실패를 조용히 삼키지 않는다).
 */
export function resolveSiteHoles(node, siteData, errors, path = '') {
  if (isHoleNode(node)) {
    const siteKey = node.$site;
    if (!(siteKey in siteData) || siteData[siteKey] === undefined) {
      errors.push(`구멍 미해결: $site:"${siteKey}" (경로: ${path || '(root)'})`);
      return node;
    }
    return siteData[siteKey];
  }
  if (Array.isArray(node)) {
    return node.map((el, i) => resolveSiteHoles(el, siteData, errors, `${path}[${i}]`));
  }
  if (node !== null && typeof node === 'object') {
    const out = {};
    for (const key of Object.keys(node)) {
      out[key] = resolveSiteHoles(node[key], siteData, errors, path ? `${path}.${key}` : key);
    }
    return out;
  }
  return node;
}

/** 치환 후 트리에 구멍이 하나라도 남아 있는지(=치환 실패가 있었는지) 재확인한다. */
export function hasRemainingHole(node) {
  if (isHoleNode(node)) return true;
  if (Array.isArray(node)) return node.some(hasRemainingHole);
  if (node !== null && typeof node === 'object') {
    return Object.values(node).some(hasRemainingHole);
  }
  return false;
}

/**
 * `compatibilityJson`의 최상위 키 중 원래 구멍이었던 것만 골라 `{ key: resolvedValue }`로
 * 돌려준다 — 전체 재직렬화가 아니라 사이트면이 실제로 채운 필드만 emit하기 위해서다.
 */
function extractSiteConstants(compatibilityJson, resolvedRoot) {
  const siteConstants = {};
  for (const key of Object.keys(compatibilityJson)) {
    if (isHoleNode(compatibilityJson[key])) {
      siteConstants[key] = resolvedRoot[key];
    }
  }
  return siteConstants;
}

/**
 * 순수 로직 진입점(파일 경로만 받고, 실제 읽기는 얇게 감싼다) — fail-closed 두 종을 여기서
 * 강제한다. 두 사이트면이 모두 없거나 구멍이 남으면 던진다(빈 값·permissive 폴백 없음).
 */
export function generateSiteModule({ compatibilityJson, siteJsonPath, siteExampleJsonPath, readFileFn = readFileSync, existsFn = existsSync }) {
  const siteExists = existsFn(siteJsonPath);
  const exampleExists = existsFn(siteExampleJsonPath);
  if (!siteExists && !exampleExists) {
    throw new Error(
      `사이트면 부재: '${siteJsonPath}'와 '${siteExampleJsonPath}'가 모두 없습니다 (§8.4 fail-closed ①)`
    );
  }

  const siteProfile = siteExists ? 'site' : 'example';
  const sitePath = siteExists ? siteJsonPath : siteExampleJsonPath;
  let siteData;
  try {
    siteData = JSON.parse(readFileFn(sitePath, 'utf8'));
  } catch (error) {
    throw new Error(`사이트면 파싱 실패(${sitePath}): ${error instanceof Error ? error.message : String(error)}`);
  }

  const errors = [];
  const resolvedRoot = resolveSiteHoles(compatibilityJson, siteData, errors);

  if (errors.length > 0 || hasRemainingHole(resolvedRoot)) {
    throw new Error(`사이트면 구멍 잔존 (§8.4 fail-closed ②):\n${errors.join('\n') || '(알 수 없는 잔존 구멍)'}`);
  }

  return { siteProfile, siteConstants: extractSiteConstants(compatibilityJson, resolvedRoot) };
}

function renderModule({ siteProfile, siteConstants }) {
  return `// AUTO-GENERATED by \`pnpm gen:site\` — 손으로 고치지 마십시오.
// 정본: docs/policy-contract.md §8.4. 이 파일은 추적되지 않습니다(src/generated/.gitignore).
//
// siteProfile==='example'이면 아래 값은 compat/site.example.json(예약 네임스페이스 전용)에서
// 왔다 — 실제 인프라 값이 아니다. 'site'면 site/site.json(영구 비추적)에서 왔다.
export const siteProfile: 'site' | 'example' = ${JSON.stringify(siteProfile)};
export const siteConstants = ${JSON.stringify(siteConstants, null, 2)} as const;
`;
}

export function main(rootOverride) {
  const root = rootOverride ?? process.env.MALGN_GEN_SITE_ROOT ?? DEFAULT_ROOT;
  const compatibilityJsonPath = join(root, 'compat', 'compatibility.json');
  const siteJsonPath = join(root, 'site', 'site.json');
  const siteExampleJsonPath = join(root, 'compat', 'site.example.json');
  const outPath = join(root, 'src', 'generated', 'siteConstants.ts');

  const compatibilityJson = JSON.parse(readFileSync(compatibilityJsonPath, 'utf8'));

  const result = generateSiteModule({ compatibilityJson, siteJsonPath, siteExampleJsonPath });

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, renderModule(result), 'utf8');
  console.log(`[gen:site] siteProfile=${result.siteProfile} → ${outPath}`);
  return result;
}

const isDirectRun = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isDirectRun) {
  try {
    main();
  } catch (error) {
    console.error(`[gen:site] 빌드 실패(fail-closed): ${error instanceof Error ? error.message : String(error)}`);
    process.exitCode = 1;
  }
}
